language: java

dist: trusty

jdk:
  - oraclejdk8
  - openjdk8

before_install:
  - chmod 777 "scripts/build.sh"
  - chmod 777 "scripts/javadoc.sh"

after_script: ./scripts/javadoc.sh

script: ./scripts/build.sh

install: true

sudo: false

env:
  global:
  - secure: Qv3lWydc65BlLDv2IGtRC1+NTOyytKOqAGOVSO5/NFvH1mX8VE1yBm+vop/S/Tj6iUxOSzxD47xDQAZt/T13SKKFUngqu83uQS4bwu8QK6aNVp2xxphLNwqprcxXIbvY4L5NxOd0lE050ITgJhyz+tVwW/0yfc7BTvw7t8iOkLI=

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: revamp

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
