language: java

dist: trusty

jdk:
  - oraclejdk8
  - openjdk8

script: ./scripts/build.sh
after_script: ./scripts/javadoc.sh

install: true
sudo: false

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: revamp
    jdk: openjdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

env:
  global:
  - secure: Qv3lWydc65BlLDv2IGtRC1+NTOyytKOqAGOVSO5/NFvH1mX8VE1yBm+vop/S/Tj6iUxOSzxD47xDQAZt/T13SKKFUngqu83uQS4bwu8QK6aNVp2xxphLNwqprcxXIbvY4L5NxOd0lE050ITgJhyz+tVwW/0yfc7BTvw7t8iOkLI=
  - secure: R5fqbgn9y+uZ8sjQul0tIrZoqqOIFBe8Peqop9onDx4/ffczZJvPkkPlI/PIYEUVRNEteSP+y1RSTGxTFNmeiX1NLWfB5mdT8dmKharKkWFuDKWwMdaOuWbdWjALT/dx4yrgY3UHsM7GO2h7T67owPL3c3k83IDlPgBI7CKSryc=
  - secure: k5SUYYpfcBsvaWuIEtjKFk/7mOVwrxrcsx7Fba5GaO4oTHuomfDRc+NS6PI92Krkm6ZNV2HNSREwTbTSLRZ2L6iR8S2z3vbcg4ZvYnDJ94DxqSgBqc/b8En9mEGv16t8Q7g+vJfjKITpgO76hS3dEKD+RFpHbxz1m8gDalsA7M4=
